theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: ADAcore website
description: Website built using the ADA template
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
